---
formatter: markdown
header-from: main.tf

sections:
  hide-all: false
  hide: []
  show-all: true
  show: []

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
  check: false

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  escape: true
  indent: 3
  required: true
  sensitive: true
  type: true
